local bot1 = teamyar.run_command (context, "175/command_15","{}")
local bot2 = teamyar.run_command (context, "175/command_16","{}")
local bot3 = teamyar.run_command (context, "175/command_17","{}")
local bot4 = teamyar.run_command (context, "175/command_18","{}")
local bot5 = teamyar.run_command (context, "175/command_19","{}")

template = [[
<!DOCTYPE html><html dir="rtl" lang="en"> <head> <meta charset="UTF-8" /> <meta name="viewport" content="width=device-width, initial-scale=1.0" /> <title>گزارش جامع صورت مالی</title> </head> <style> .tab { overflow: hidden; border: 1px solid #ccc; background-color: #0071c5; float: right; margin-bottom: 10px; border-radius: 30px; } .tab button { background-color: inherit; float: right; border: none; outline: none; cursor: pointer; padding: 14px 16px; transition: 0.3s; font-size: 17px; color: #f0f8ff; } .tab button:hover { background-color: #f0f8ff; color: #0047ab; border-radius: 30px; } .tab button.active { background-color: #00308f; color: #f0f8ff; border-radius: 30px; } .tabcontent { display: none; padding: 6px 12px; border: 1px solid #ccc; border-top: none; } .activecontent { display: block; } h2 { margin-top: 0; } </style> <body> <h2>گزارش جامع صورت مالی</h2> <div class="tab active"> <button class="tablinks active" onclick="changeTab(event, 'ProfitAndLossFinancialStatement')" > سود و زیان </button> <button class="tablinks" onclick="changeTab(event, 'TotalProfitAndLossFinancialStatement')" > سود و زیان جامع </button> <button class="tablinks" onclick="changeTab(event, 'FinancialStatements')" > وضعیت مالی </button> <button class="tablinks" onclick="changeTab(event, 'ChangesOwnershipRights')" > تغییرات در حقوق مالکانه </button> <button class="tablinks" onclick="changeTab(event, 'StatementCashFlows')"> جریان های نقدی </button> </div> <div id="ProfitAndLossFinancialStatement" class="tabcontent activecontent"> %s </div> <div id="TotalProfitAndLossFinancialStatement" class="tabcontent">%s</div> <div id="FinancialStatements" class="tabcontent">%s</div> <div id="ChangesOwnershipRights" class="tabcontent">%s</div> <div id="StatementCashFlows" class="tabcontent">%s</div> <script> function changeTab(evt, tabName) { var i, tabcontent, tablinks; tabcontent = document.getElementsByClassName("tabcontent"); for (i = 0; i < tabcontent.length; i++) { tabcontent[i].style.display = "none"; } tablinks = document.getElementsByClassName("tablinks"); for (i = 0; i < tablinks.length; i++) { tablinks[i].className = tablinks[i].className.replace(" active", ""); } document.getElementById(tabName).style.display = "block"; evt.currentTarget.className += " active"; } </script> </body></html>
]]

local res = string.format(template, bot1, bot2, bot3, bot4, bot5)
teamyar.write_result(context, res)