if(ty__main.BOT_LANG == undefined ){
ty__main.BOT_LANG  = {
  'Business_Bank_Account':'Business Bank Account',
  'account_watchlist': 'account watchlist',
  'Total_Cash_InAndOut': 'Total Cash InAndOut',
  'Discrepancy_of_items':'Discrepancy of items',
  'Expense_claims':'Expense claims',
  'Revenue vs Expenses' : 'Revenue vs Expenses',
  'Total_Cash_InAndOut': 'Total cash in and out',  
  'DailyDepositsWithdrawals':'Daily Deposits and Withdrawals',
  'Deposits':'Deposits',
  'Withdrawals':'Withdrawals',
  'Price': 'Price',
  'current_day': 'Current day',

    //زینب محمدی
  'project_ID':'Project Name',
  'BOT_TOTAL_EXPENSE':'Total Expense',
  'PROJECT_OPENED':'Opened Project',
  'PROJECT_CLOSED':'Closed Project',
  'TOTAL_PROJECT':'Total Project',
  'SUM_PAYABLE':'Billable',
  'SUM_NO_PAYABLE':'Non Billable',
  'TIMESHEET_SUMMARY':'Time Sheet Summary',
  'PROJECT_EXPENSE_CHART':'Expense Summary',
  'PROJECT_MILESTONE_STATUS_CHART':'Milestone Status',
  'TIMESHEET_SUMMARY':'Time Sheet Summary',
  'PROJECT_STAGE_STATUS_CHART':'Project Task Status',
  'SUM_ALL':'Total',
  'PERCENT':'Percent',
  'TIME_WORK':'Time Of Work',
  'TIME_REST':'Time Of Rest',
  'FIRST_INPUT':'First Input',
  'LAST_OUTPUT':'Last Output',
  'STATUS':'Status',
  'EXIT_OF_SYS':'Exit Of System',
  'ACTIVE':'Active',
  'NOT_ACTIVE':'In Rest',
  'TELE_WORK_INFO':'Remote Work Info',
  'DATE_EXPIRE_LICENCE':'Date Expire Licence',
  'PACKAGES':'Packages',
  'LICENCE_INFO':'Licence Info',
  'POSITION_TI':'Position',
  'CHAT_BY_TOPIC':'Chats By Topic',
  'NO_SUBJECT':'No Subject',
  'CHAT_BY_DURATION_TIME':'Chat By Duration Time',
  'NO_RESPONSE':'No Response',
  'CHAT_BY_RESPONSE_TIME':'Chat By Responnnse Time',
  'COUNT_EMAILS_IN_BOX':'Count Emails In Boxes',
  'SUM_ACTIVE':'Sum Active Users',
  'SUM_NOT_ACTIVE':'Sum Not Active Users',
  'CHAT_ONLINE_USERS_IN_GROUP':'Count Online User In Chat Group',
  'CHAT_GROUP':'chat Group',
  'PROJECT_STAGE_PROGRESS_CHART':'Project Stage Progress',
  'PROJECT_STAGE_TODO_STATUS_CHART':'Project Progress Status',
  'DRAFT_STATE':'Draft',
  'DONE_STATE':'Done',
  'DO_STATE':'Doing',
  'CHECK_STATE':'Checking',
  'PROJECT_TODO_PROGRESS':'Project Todo Progress',
  'STATUS_SUSPEND':' Suspended',
  'PROJECT_STAGES_STATUS_CHART':'Project Todo Stage Status',
  'STATUS_CLOSE':'Closed',
  'STATUS_OPEN':'Opened',
  'GROUP_ID':'Group Name',
  'BUDJET':'Budjet',
  'AC_EX':'Actual Expence',
  'PRE_EX':'Predicted Expence',
  'PLAN_EX':'Planned EXpence',
  'INVOICE':'Invoice',
  'PROJECT_BUDJET_STATUS_CHART':'Project Budjet Status Chart',
  'PAYABLE':'Billable',
  'NOT_PAYABLE':'Non Billable',
  'PROJECT_TIMESHEET_SUMMARY_CHART':'Project TimeSheet Summary Chart',
  'BOT_EVALUATE_INFO':'Evaluate Info',
  'PROJECT_TAG':'Sum Of Project Stage Tag',
  'ACCOUNTING_TOTAL REVENUE_CHART':'Annual Total Revenue',
  
  // صابری
   'COMPARE_PERSONNEL_BASED_ON_SEX': 'Compare personnel based on their sex',   
  'FEMALE_TO_MALE_RATIO': 'Female to male ratio',  
  'PERCENTAGE': 'Percentage',  
  'MEN': 'MAN',   
  'WOMEN': 'WOMAN',   
  'NOTICES_DURING_FIRST_YEAR_BY_AGE_GROUP': 'Time to quit the job based on age group',    
  'TIME_TO_QUIT_THE_JOB': 'Time to quit the job based on year',  
  'YEARS_AT_COMPANY': 'Years at company',  
  'YEAR': 'Year',   
  'PART_TIME_VS_FULL_TIME': 'Part time vs. full time',     
  'FULL_TIME': 'Full time',   
  'PART_TIME': 'Part time',     
  'ORG_ID': 'Organization',   
  'FISCAL_ID': 'Fiscal year',  
  'PROCUREMENT_PLANS': 'Procurement plans',   
  'PLANNED': 'Planned',  
  'APPROVED': 'Approved',   
  'POSTPONED': 'Postponed',   
  'PURCHASE_ORDERS': 'Purchase orders',   
  'INTERNAL_MOBILITY': 'Internal mobility',   
  'OF_ALL_DIRECTOR_AND_MANAGING_DIRECTOR_ROLES_WERE_FILLED_INTERNALLY': 'of all director and managing director roles were filled internally.',     
  'POSITIONS': 'Postitions',   
  'FROM': 'from',   
  'OPEN_POSITIONS_WHERE_FILLED_THROUGH_OUR_INTERNAL_RECRUITING_INITIATIVES': 'Open positions were filled through our internal recruiting initiatives',  
  'OF_ALL_VACANCIES_WERE_FILLED_INTERNALLY': 'of all vacancies were filled internally',    
  'PROCUREMENT_PLANS_OVERALL': 'Procurement plans overall',    
  'DRAFT': 'Draft',   
  'CHECK': 'Check',   
  'DO': 'Do',    
  'COMPLETED': 'Completed',    
  'DELETED': 'Deleted',     
  'QUANTITY': 'Quantity',    
  'ST0': 'Draft',   
  'ST1': 'Check',    
  'ST2': 'Do',    
  'ST3': 'Complete',   
  'PURCHASE_ORDERS_OVERALL': 'Purchase orders overall',    
  'SETT': 'Settlement',   
  "PURCHASE_INVOICE": 'Purchase invoice',    
  "PURCHASE_INVOICE_OVERALL": 'Purchase invoice overall',  
  'VENDORS': 'Vendros',    
  'NO_OF_VENDORS': 'Nomber of vendors',  
  'VENDORS_IN_CONTRACT': 'Vencdors in contract',    
  'MONEY_SPEND_FOR_ORDERS': 'Money spend for orders',  
  'TOTAL_COST': 'Total cost',   
  'AMOUNT_PAID': 'Amount paid',  
  'AMOUNT_TO_PAY': 'Amount to pay',  
  'PURCHASE_ORDER': 'Purchase order',    
  'THE_AMOUNT_OF_PURCHASES_FROM_SUPPLIERS_BY_MONTH': 'The amount of purchased from supplires by month',   
  'CLIENT_ID': 'Clients',
  'PROCUREMENT_STATUS_OVERALL': 'Procurement Status (Overall)',
  
    // صالحی
  'FILE_ICON':'Icon',
  'FILE_NAME':'Name',
  'FILE_SIZE':'Size',
  'TIME_MODIFY':'Modified Date ',
  'CONFIRM_STATUS':'Status',
  'ASSIGN_DATE':'Update date',
  'AUTHOR':'Author',
  'DATE_CREATE':'Date create',
  'RECENT_DOCUMENTS':'Recent Documents',
  'PENDING_DOCUMENTS':'Pending Documents',
  'RECENT_ACTIVITIES':'Recent Activities',
  'DOCUMENTS_SUMMARY':'Documents Summary',
  'APPROVED':'Approved',
  'REJECTED':'Rejected',
  'PENDING':'Pending',
  'DOCUMENTS_STATUS_IN_ORGANIZATION_UNITS':'Documents Status In Organization Units',
  'META_DATA':'Metadata',
  'COUNT':'Count',
  'SIGNED_DEALS_BY_PIPELINE':'Signed deals by pipeline',
  'SECTION':'Section',
  'SENT_EMAIL':'Sent email',
  'CLOSED_DEALS':'Close deals',
  'LOST_DEALS':'Lost deals',
  'WIN_RATE':'Win rate',
  'LEADS_BY_SOURCE':'Leads by source',
   'TO':'To',
  	//zahiri
  'TOTAL_BALANCE' : 'Total balance',
}
}
