if(ty__main.BOT_LANG == undefined ){
ty__main.BOT_LANG  = {
  'Business_Bank_Account':'حساب های بانکی',
  'account_watchlist' : 'لیست پیگیری حسابها',
  'Discrepancy_of_items':'مغایرت گیری آیتم ها',
  'Expense_claims':'درخواست های هزینه',
  'Revenue vs Expenses' : 'درآمد و هزینه ها',
  'Total_Cash_InAndOut': 'جریان کلی وجه نقد ورودی و خروجی',
  'DailyDepositsWithdrawals':'واریزها و برداشت های روزانه ',
  'Deposits':'واریز',
  'Withdrawals':'برداشت',
  'Price': 'قیمت',
  'current_day': 'روز جاری',
  
    //zynab mohammadi 
  'project_ID':'نام پروژه',
  'PROJECT_OPENED':'پروژه های باز',
  'PROJECT_CLOSED':'پروژه های بسته',
  'TOTAL_PROJECT':'کل پروژه ها',
  'TIMESHEET_SUMMARY':'خلاصه جدول زمانی',
'PROJECT_EXPENSE_CHART':'خلاصه هزینه',
'PROJECT_MILESTONE_STATUS_CHART':'وضعیت اهداف کلیدی',
  'SUM_PAYABLE':'قابل پرداخت',
  'SUM_NO_PAYABLE':' غیر قابل پرداخت',
  'PROJECT_STAGE_STATUS_CHART':' وضعیت مراحل پروژه ',
  'TIMESHEET_SUMMARY':'خلاصه جدول زمانی',
  'SUM_ALL':'کل',
  'PERCENT':'Percent ',
  'TIME_WORK':'مدت زمان فعالیت ',
  'TIME_REST':'مدت زمان استراحت',
  'FIRST_INPUT':'اولین ورود',
  'LAST_OUTPUT':'آخرین خروج',
  'STATUS':'وضعیت فعلی',
  'EXIT_OF_SYS':'خروج از سیستم',
  'ACTIVE':'فعال',
  'NOT_ACTIVE':'غیر فعال',
  'TELE_WORK_INFO':'اطلاعات دورکاری',
  'DATE_EXPIRE_LICENCE':'تاریخ انقضاء مجوز',
  'PACKAGES':'بسته ها',
  'LICENCE_INFO':'اطلاعات مجوز',
  'POSITION_TI':'سمت',
  'CHAT_BY_TOPIC':'تعداد گفتگو ها به تفکیک موضوعات',
  'NO_SUBJECT':'بدون موضوع',
  'CHAT_BY_DURATION_TIME':'مدت زمان گفتگو ها',
  'NO_RESPONSE':'بدون پاسخ',
  'CHAT_BY_RESPONSE_TIME':'مدت زمان اولین پاسخ و انتظار گفتگو ها',
  'COUNT_EMAILS_IN_BOX':'تعداد نامه ها در صندوق های پستی  من ',
  'SUM_ACTIVE':'مجموع کاربران فعال',
  'SUM_NOT_ACTIVE':'مجموع کاربران غیر فعال',
  'CHAT_ONLINE_USERS_IN_GROUP':'تعداد کاربران فعال در گروه های گفتگو',
  'CHAT_GROUP':'گروه گفتگو',
  'PROJECT_STAGE_PROGRESS_CHART':'درصد پیشرفت مراحل پروژه',
  'PROJECT_STAGE_TODO_STATUS_CHART':'وضعیت پیشرفت پروژه',
  'DRAFT_STATE':'پیش نویس',
  'DONE_STATE':'کامل',
  'DO_STATE':'در حال اجرا',
  'CHECK_STATE':'بررسی',
  'PROJECT_TODO_PROGRESS':'درصد پیشرفت پروژه',
  'STATUS_SUSPEND':'موکول شده',
  'PROJECT_STAGES_STATUS_CHART':'وضعیت  اقدام های مرحله های پروژه',
  'STATUS_CLOSE':'بسته شده',
  'STATUS_OPEN':'باز',
  'GROUP_ID':'نام گروه',
  'BUDJET':'بودجه',
  'AC_EX':'هزینه واقعی',
  'PRE_EX':'هزینه پیش بینی شده ',
  'PLAN_EX':'هزینه برنامه ریزی شده',
  'INVOICE':'صورتحساب',
  'PROJECT_BUDJET_STATUS_CHART':'نمایش صورت وضعیت مالی پروژه',
  'PAYABLE':'قابل پرداخت',
  'NOT_PAYABLE':'غیر قابل پرداخت',
  'PROJECT_TIMESHEET_SUMMARY_CHART':'خلاصه جدول زمانی پروژه',
  'BOT_TOTAL_EXPENSE':'گزارش مجموع هزینه ها',
  'BOT_EVALUATE_INFO':'گزارش نتایج کیفیت ',
  'PROJECT_TAG':'مجموع تگ های مرحله های پروژه',
  'ACCOUNTING_TOTAL REVENUE_CHART':'نمودار مجموع درآمد سالیانه ',

  // صابری
    'COMPARE_PERSONNEL_BASED_ON_SEX':'مقایسه پرسنل بر اساس جنسیت', 
  'FEMALE_TO_MALE_RATIO':'نسبت زن به مرد',  
  'PERCENTAGE':'درصد',    
  'MEN':'مذکر',    
  'WOMEN':'مونث',  
  'NOTICES_DURING_FIRST_YEAR_BY_AGE_GROUP':'درصد ترک کار پرسنل بر اساس گروه سنی',   
  'TIME_TO_QUIT_THE_JOB':'درصد ترک کار پرسنل بر اساس سال ',  
  'YEARS_AT_COMPANY': 'ماندگاری', 
  'YEAR':'سال',  
  'PART_TIME_VS_FULL_TIME':'مقایسه تعداد پرسنل تمام وقت در برابر پاره وقت', 
  'FULL_TIME': 'تمام وقت',  
  'PART_TIME':'پاره وقت',  
  'ORG_ID':'شعبه', 
  'FISCAL_ID':'سال مالی',  
  'PROCUREMENT_PLANS': 'برنامه‌های تدارکات',  
  'PLANNED': 'برنامه‌ریزی شده',  
  'APPROVED': 'تایید شده', 
  'POSTPONED':'موکول شده',  
  'PURCHASE_ORDERS':'سفارشات خرید', 
  'INTERNAL_MOBILITY':'انتصابات داخلی', 
  'OF_ALL_DIRECTOR_AND_MANAGING_DIRECTOR_ROLES_WERE_FILLED_INTERNALLY':'پست‌های مدیریتی به صورت داخلی پر شده‌اند.',  
  'POSITIONS':'موقعیت شغلی',  
  'FROM':'از', 
  'OPEN_POSITIONS_WHERE_FILLED_THROUGH_OUR_INTERNAL_RECRUITING_INITIATIVES':'موقعیت شغلی خالی به صورت داخلی پر شده‌اند.',  
  'OF_ALL_VACANCIES_WERE_FILLED_INTERNALLY':'از موقعیت‌های شغلی به صورت داخلی پر شده‌اند.',   
  'PROCUREMENT_PLANS_OVERALL':'وضعیت تدارکات (کلی)',  
  'DRAFT':'پیش‌نویس', 
  'CHECK':'بررسی', 
  'DO':'اجرا',  
  'COMPLETED':'کامل',  
  'DELETED':'باطل شده',  
  'QUANTITY':'تعداد', 
  'ST0':'پیش‌نویس',
  'ST1':'بررسی',
  'ST2':'اجرا', 
  'ST3':'کامل',  
  'PURCHASE_ORDERS_OVERALL':'سفارشات خرید (کلی)',
  'SETT':'تسویه شده',  
  "PURCHASE_INVOICE":'فاکتورهای خرید',  
  "PURCHASE_INVOICE_OVERALL":'فاکتورهای خرید (کلی)', 
  'VENDORS':'تامین‌کنندگان', 
  'NO_OF_VENDORS':'تعداد تامین‌کنندگان',  
  'VENDORS_IN_CONTRACT':'تامین‌کنندگان فعال',  
  'MONEY_SPEND_FOR_ORDERS':'مبلغ پرداخت شده برای سفارشات (پیش پرداخت)',  
  'TOTAL_COST':'مبلغ کل',   
  'AMOUNT_PAID':'مبلغ پرداختنی',  
  'AMOUNT_TO_PAY':'مانده پرداختی',  
  'PURCHASE_ORDER':'سفارش خرید',   
  'THE_AMOUNT_OF_PURCHASES_FROM_SUPPLIERS_BY_MONTH':'میزان خرید از تامین کنندگان به تفکیک ماه',  
  'CLIENT_ID':'تامین‌کننده',
  'PROCUREMENT_STATUS_OVERALL': 'وضعیت تدارکات (کلی)',
 
  // صالحی
  'FILE_ICON':'آیکون',
  'FILE_NAME':'نام',
  'FILE_SIZE':'سایز',
  'TIME_MODIFY':'تاریخ تغییر ',
  'CONFIRM_STATUS':'وضعیت',
  'ASSIGN_DATE':'تاریخ به روز رسانی',
  'AUTHOR':'ایجاد کننده',
  'DATE_CREATE':'تاریخ ایجاد',
  'RECENT_DOCUMENTS':'آخرین اسناد بارگذاری شده',
  'PENDING_DOCUMENTS':'اسناد در حال بررسی',
  'RECENT_ACTIVITIES':'فعالیت های اخیر',
  'DOCUMENTS_SUMMARY':'خلاصه وضعیت اسناد',
  'APPROVED':'تایید شده',
  'REJECTED':'رد شده',
  'PENDING':'در انتظار',
  'DOCUMENTS_STATUS_IN_ORGANIZATION_UNITS':'وضعیت اسناد در واحد های سازمان',
  'META_DATA':'متادیتا',
  'COUNT':'تعداد',
  'SIGNED_DEALS_BY_PIPELINE':'قرارداهای امضا شده به تفکیک ذینفعان',
  'SECTION':'بخش',
  'SENT_EMAIL':'ایمیل های ارسال شده',
  'CLOSED_DEALS':'معاملات بسته شده',
  'LOST_DEALS':'معاملات از دست رفته',
  'WIN_RATE':'نرخ سود',
  'LEADS_BY_SOURCE':'منابع ارتباطی',
   'TO':'تا',

}
}

